function comp()
{
  echo "File = " $1
  diff -w ../jd17/$1 $1
}

comp catalogue/Basket.java
comp catalogue/BetterBasket.java
comp catalogue/Product.java
comp clients/backDoor/BackDoorClient.java
comp clients/backDoor/BackDoorController.java
comp clients/backDoor/BackDoorModel.java
comp clients/backDoor/BackDoorView.java
comp clients/cashier/CashierClient.java
comp clients/cashier/CashierController.java
comp clients/cashier/CashierModel.java
comp clients/cashier/CashierView.java
comp clients/collection/CollectClient.java
comp clients/collection/CollectController.java
comp clients/collection/CollectModel.java
comp clients/collection/CollectView.java
comp clients/customer/CustomerClient.java
comp clients/customer/CustomerController.java
comp clients/customer/CustomerModel.java
comp clients/customer/CustomerView.java
comp clients/Main.java
comp clients/Picture.java
comp clients/PosOnScrn.java
comp clients/Setup.java
comp clients/shopDisplay/DisplayClient.java
comp clients/shopDisplay/DisplayController.java
comp clients/shopDisplay/DisplayModel.java
comp clients/shopDisplay/DisplayView.java
comp clients/warehousePick/PickClient.java
comp clients/warehousePick/PickController.java
comp clients/warehousePick/PickModel.java
comp clients/warehousePick/PickView.java
comp clients/WebCustomerClient.java
comp dbAccess/DBAccess.java
comp dbAccess/DBAccessFactory.java
comp dbAccess/DerbyAccess.java
comp dbAccess/DerbyCreateAccess.java
comp dbAccess/LinuxAccess.java
comp dbAccess/StockR.java
comp dbAccess/StockRW.java
comp dbAccess/WindowsAccess.java
comp debug/DEBUG.java
comp middle/F_Order.java
comp middle/F_StockR.java
comp middle/F_StockRW.java
comp middle/LocalMiddleFactory.java
comp middle/MiddleFactory.java
comp middle/Names.java
comp middle/OrderException.java
comp middle/OrderProcessing.java
comp middle/RemoteMiddleFactory.java
comp middle/Server.java
comp middle/StockException.java
comp middle/StockReader.java
comp middle/StockReadWriter.java
comp orders/Order.java
comp orders/OrderTest.java
comp remote/RemoteOrder_I.java
comp remote/RemoteStockRW_I.java
comp remote/RemoteStockR_I.java
comp remote/R_Order.java
comp remote/R_StockR.java
comp remote/R_StockRW.java
